/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as PlaygroundLayoutRouteImport } from './../routes/playground/layout'
import { Route as PageRouteImport } from './../routes/page'
import { Route as PlaygroundPageRouteImport } from './../routes/playground/page'

const PlaygroundLayoutRoute = PlaygroundLayoutRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundPageRoute = PlaygroundPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaygroundLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/playground': typeof PlaygroundLayoutRouteWithChildren
  '/playground/': typeof PlaygroundPageRoute
}
export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/playground': typeof PlaygroundPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/playground': typeof PlaygroundLayoutRouteWithChildren
  '/playground/': typeof PlaygroundPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/playground' | '/playground/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/playground'
  id: '__root__' | '/' | '/playground' | '/playground/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  PlaygroundLayoutRoute: typeof PlaygroundLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundPageRouteImport
      parentRoute: typeof PlaygroundLayoutRoute
    }
  }
}

interface PlaygroundLayoutRouteChildren {
  PlaygroundPageRoute: typeof PlaygroundPageRoute
}

const PlaygroundLayoutRouteChildren: PlaygroundLayoutRouteChildren = {
  PlaygroundPageRoute: PlaygroundPageRoute,
}

const PlaygroundLayoutRouteWithChildren =
  PlaygroundLayoutRoute._addFileChildren(PlaygroundLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  PlaygroundLayoutRoute: PlaygroundLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
